apiVersion: v1
kind: Secret
metadata:
    name: {{ template "neosync-api.fullname" . }}-service-evs
    namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
    AUTH0_BASEURL: {{ .Values.auth0.baseUrl }}
    AUTH0_AUDIENCE: {{ .Values.auth0.audience }}
    AUTH0_CLIENTID_SECRET: {{ .Values.auth0.clientMap | toJson | quote }}

    AUTH0_MGMT_BASEURL: {{ .Values.auth0.mgmtBaseUrl }}
    AUTH0_MGMT_CLIENT_ID: {{ .Values.auth0.mgmtClientId }}
    AUTH0_MGMT_CLIENT_SECRET: {{ .Values.auth0.mgmtClientSecret }}

    DB_HOST: {{ .Values.db.host }}
    DB_PORT: {{ .Values.db.port | quote }}
    DB_NAME: {{ .Values.db.name }}
    DB_USER: {{ .Values.db.username }}
    DB_PASS: {{ .Values.db.password }}

    {{- if .Values.host }}
    HOST: {{ .Values.host | quote}}
    {{- end }}

    PORT: {{ .Values.port | quote }}

    {{- if ne .Values.nucleusEnv "dev" }}
    OTEL_EXPORTER_OTLP_PORT: "4317" # sends to gRPC receiver on port 4317
    {{- end }}

    NUCLEUS_ENV: {{ .Values.nucleusEnv }}

    SHUTDOWN_TIMEOUT_SECONDS: {{ .Values.shutdownTimeoutSeconds | quote }}
